### ISSUE TITLE
Auto Login 기능 오작동

### ISSUE THREAD

**Issue by raiiiny** [chuhyeonjin/sorry-field-extension#3]
![image](https://user-images.githubusercontent.com/64065435/135115488-b801d69e-e265-4872-9c18-fe627859cdbe.png)

Uncaught TypeError: Cannot read properties of undefined (reading 'page')

**Comment by qqtq** [comment]
개발 중인 코드를 삭제하지 않고 드려서 그렇습니다
새로 드리겠습니다
